# Generated by Django 5.1.4 on 2025-01-16 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera_feed_app', '0002_alter_machine_cluster'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraSwitchTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'CameraSwitchTime',
            },
        ),
    ]
